// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.27.1
// source: proto/matching.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PbTradeTick struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SymbolId      string                 `protobuf:"bytes,1,opt,name=symbol_id,json=symbolId,proto3" json:"symbol_id,omitempty"`
	TradeId       int64                  `protobuf:"varint,2,opt,name=trade_id,json=tradeId,proto3" json:"trade_id,omitempty"`
	Price         string                 `protobuf:"bytes,3,opt,name=price,proto3" json:"price,omitempty"`
	Quantity      string                 `protobuf:"bytes,4,opt,name=quantity,proto3" json:"quantity,omitempty"`
	TradeTime     int64                  `protobuf:"varint,5,opt,name=trade_time,json=tradeTime,proto3" json:"trade_time,omitempty"` // epoch millis
	TakerSide     string                 `protobuf:"bytes,6,opt,name=taker_side,json=takerSide,proto3" json:"taker_side,omitempty"`  // BUY or SELL
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PbTradeTick) Reset() {
	*x = PbTradeTick{}
	mi := &file_proto_matching_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PbTradeTick) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PbTradeTick) ProtoMessage() {}

func (x *PbTradeTick) ProtoReflect() protoreflect.Message {
	mi := &file_proto_matching_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PbTradeTick.ProtoReflect.Descriptor instead.
func (*PbTradeTick) Descriptor() ([]byte, []int) {
	return file_proto_matching_proto_rawDescGZIP(), []int{0}
}

func (x *PbTradeTick) GetSymbolId() string {
	if x != nil {
		return x.SymbolId
	}
	return ""
}

func (x *PbTradeTick) GetTradeId() int64 {
	if x != nil {
		return x.TradeId
	}
	return 0
}

func (x *PbTradeTick) GetPrice() string {
	if x != nil {
		return x.Price
	}
	return ""
}

func (x *PbTradeTick) GetQuantity() string {
	if x != nil {
		return x.Quantity
	}
	return ""
}

func (x *PbTradeTick) GetTradeTime() int64 {
	if x != nil {
		return x.TradeTime
	}
	return 0
}

func (x *PbTradeTick) GetTakerSide() string {
	if x != nil {
		return x.TakerSide
	}
	return ""
}

var File_proto_matching_proto protoreflect.FileDescriptor

const file_proto_matching_proto_rawDesc = "" +
	"\n" +
	"\x14proto/matching.proto\x12\bmatching\"\xb5\x01\n" +
	"\vPbTradeTick\x12\x1b\n" +
	"\tsymbol_id\x18\x01 \x01(\tR\bsymbolId\x12\x19\n" +
	"\btrade_id\x18\x02 \x01(\x03R\atradeId\x12\x14\n" +
	"\x05price\x18\x03 \x01(\tR\x05price\x12\x1a\n" +
	"\bquantity\x18\x04 \x01(\tR\bquantity\x12\x1d\n" +
	"\n" +
	"trade_time\x18\x05 \x01(\x03R\ttradeTime\x12\x1d\n" +
	"\n" +
	"taker_side\x18\x06 \x01(\tR\ttakerSideB Z\x1equote-ticker/internal/model/pbb\x06proto3"

var (
	file_proto_matching_proto_rawDescOnce sync.Once
	file_proto_matching_proto_rawDescData []byte
)

func file_proto_matching_proto_rawDescGZIP() []byte {
	file_proto_matching_proto_rawDescOnce.Do(func() {
		file_proto_matching_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_matching_proto_rawDesc), len(file_proto_matching_proto_rawDesc)))
	})
	return file_proto_matching_proto_rawDescData
}

var file_proto_matching_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_proto_matching_proto_goTypes = []any{
	(*PbTradeTick)(nil), // 0: matching.PbTradeTick
}
var file_proto_matching_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_matching_proto_init() }
func file_proto_matching_proto_init() {
	if File_proto_matching_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_matching_proto_rawDesc), len(file_proto_matching_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_matching_proto_goTypes,
		DependencyIndexes: file_proto_matching_proto_depIdxs,
		MessageInfos:      file_proto_matching_proto_msgTypes,
	}.Build()
	File_proto_matching_proto = out.File
	file_proto_matching_proto_goTypes = nil
	file_proto_matching_proto_depIdxs = nil
}
